[package]
name = "circuitsim-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
enum_dispatch = "0.3.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
slotmap = "1.0.7"
